model:
    type: dsgcn
    kwargs:
        feature_dim: 256
        featureless: False
        reduce_method: max
        hidden_dims: [512, 64]

workers_per_gpu: 1
batch_size_per_gpu: 1

base_lr: 0.01
lr_mults: [0.1, 0.1, 0.1]
lr_steps: [3000, 24000, 27000]
max_iter: 30000

momentum: 0.9
weight_decay: 0.0001

print_freq: 100
test_interval: 2000

train_data:
    feat_path: ./data/features/part0_train.bin
    meta_path: ./data/labels/part0_train.meta
    proposal_folders:
        - ./data/cluster_proposals/part0_train/faiss_k_80_th_0.7_step_0.05_minsz_3_maxsz_300_iter0/proposals/
        - ./data/cluster_proposals/part0_train/faiss_k_80_th_0.75_step_0.05_minsz_3_maxsz_300_iter0/proposals/

test_data:
    wo_weight: False
    feat_path: ./data/features/part1_test.bin
    meta_path: ./data/labels/part1_test.meta
    proposal_folders:
        - ./data/cluster_proposals/part1_test/faiss_k_80_th_0.7_step_0.05_minsz_3_maxsz_300_iter0/proposals/
        - ./data/cluster_proposals/part1_test/faiss_k_80_th_0.75_step_0.05_minsz_3_maxsz_300_iter0/proposals/
